### ISSUE TITLE
Want to be a contributor? Help us translating Vietnamese <=> English

### ISSUE THREAD

**Issue by nvh95** [webuild-community/advent-of-frontend#18]
## Motivation

The targeted audience of this event in the first place is Vietnamese engineers. However, the content is so good and I guess there are many non-Vietnamese engineers they might want to read these notes. It's also a good chance to advertise Vietnamese's intellect to the world.

## TODO:

- [ ] Write a Contributing Guide for new comers to contribute translating
- [ ] Form a workflow. Example: issue => claim => PR => Merge

## Post needs translation

- [ ] #20
- [ ] #21
- [ ] #22
- [ ] #23
- [ ] #24
- [ ] #25
- [ ] #26
- [ ] #27
- [ ] #28
- [ ] #29
- [ ] #30
- [ ] #31
- [ ] #32
- [ ] #33
- [ ] #34
- [ ] #35
- [ ] #36
- [ ] #37
- [ ] #38
- [ ] #39
- [ ] #40
- [ ] #41
- [ ] #42
- [ ] #43
- [ ] #44
- [ ] #45
- [ ] #46
- [ ] #47
- [ ] #48
- [ ] #49

**Comment by huytd** [comment]
Look like Github has a feature called "Convert to issue" for todo lists, so one might able to claim a post for translation by clicking on the circle button on the right of an item.

- [ ] Day 01: What's the HSL?
- [ ] Day 02: Dùng Radix Primitives với Tailwind như nào?
- [ ] Day 03: Như thế nào là một font tiếng Việt tốt?
- [ ] Day 04: Clone website một cách có hiệu quả với Vite
- [ ] Day 05: Reduce Motion
- [ ] Day 06: Calculating nested border radius
- [ ] Day 07: Animation Performance trên web hiệu quả
- [ ] Day 08: Runtime check với Literal Union Types trong TypeScript
- [ ] Day 09: Hãy nói về User Activation
- [ ] Day 10: Improve your site security with this one weird trick
- [ ] Day 11: Make your site talk with Web Speech API
- [ ] Day 12: Avoid extra useless function in React with useReducer
- [ ] Day 13: Flexbox Layout hoạt động như thế nào?
- [ ] Day 14: Reverse proxy/API Gateway on Vercel with vercel.json rewrites or Next.js rewrites
- [ ] Day 15: Spreading (React) props in TypeScript
- [ ] Day 16: You can’t change the stacking context but you can change the stacking context
- [ ] Day 17: You probably using setTimeout wrong
- [ ] Day 18: Why you should care about half pixel?
- [ ] Day 19: Tay nắm cửa trong cuộc sống hằng ngày
- [ ] Day 20: Chơi chữ cùng Variable Fonts
- [ ] Day 21: Debugging vấn đề về performance với PerformanceObserver
- [ ] Day 22: Có cần sử dụng debounce trong React 18 không?
- [ ] Day 23: Tối ưu Docker Image Size cho Next.js App
- [ ] Day 24: Vì sao bạn nên ngưng sử dụng unload event và event listener?
- [ ] Day 25: Tips to improve canvas performance
- [ ] Day 26: Javascript Obfuscator and how it actually works
- [ ] Day 27: 60 khung hình một giây
- [ ] Day 28: Những viewport units mới trong CSS: Bự Nhỏ và Linh Động (đậy)
- [ ] Day 29: Hướng dẫn dùng Chrome DevTools để đo runtime performance
- [ ] Day 30: SSR Hydration

**Comment by nvh95** [comment]
@huytd Sure. And we can pre-create all the issues first for future contributors to claim (with `good first issue` tag)
